version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn run test:auto
workflows:
  test:
    jobs:
      - test
