name: Package Size

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Mona the Octocat"
        id: hello
      - uses: preactjs/compressed-size-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
